# Generated by Django 3.1.1 on 2020-09-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id_mesero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('calificacion_mesero', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado_mesa',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='platos',
            name='calificacion_plato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.mesero'),
        ),
    ]
