# Generated by Django 3.1.1 on 2020-09-18 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.factura'),
        ),
    ]
